GET http://localhost:3001/health
###

GET http://localhost:3001/users
Content-Type: application/json
Authorization: Bearer 
###

# CADASTRO
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "Fulano",
  "email": "fulano@email.com",
  "password": "123456",
  "role": "CLIENT"
}
###

POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@wjt.com",
  "password": "123456",
  "role": "ADMIN"
}
###

# LOGIN // DAS CONTAS CADASTRADAS
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "admin@wjt.com",
  "password": "123456",
  "role": "ADMIN"
}
###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "fulano@email.com",
  "password": "123456",
  "role": "CLIENT"
}
###

# ATUALIZAR // ADICIONAR ID
PUT http://localhost:3001/users/1
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Fulane",
  "email": "fulane@wjt.com",
  "password": "1234567"
}
###

# DELETAR // ADICIONAR ID
DELETE http://localhost:3001/users/3
Authorization: Bearer 
###

///////////////////////////////////////////////////////////////////////////////////////////////////

GET http://localhost:3001/products
Content-Type: application/json
###

# BUSCAR PRODUTO ESPECIFICO // ADICIONAR ID
GET http://localhost:3001/products/
Content-Type: application/json
###

# CRIAR PRODUTO NA LOJA
POST http://localhost:3001/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5Ad2p0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc4MjI0NDIzNywiZXhwIjoxNzgyMjQ2MDM3fQ.zLhI99H_UyTZ0xvf0WcjguDAHsYpU058jB7LHyB-MmU

{
  "name": "Motoserra",
  "description": "A gasolina.",
  "price": 359.99,
  "stock": 45,
  "categoryId": 1
}
###

# ATUALIZAR // ADICIONAR ID
PUT http://localhost:3001/products/2
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Motoserra",
  "description": "A bateria.",
  "price": 599.90,
  "stock": 40
}
###

# DELETAR PRODUTO // ADICIONAR ID
DELETE http://localhost:3001/products/2
Content-Type: application/json
Authorization: Bearer 