GET http://localhost:3001/health
###

GET http://localhost:3001/users
Content-Type: application/json
Authorization: Bearer 
###

# CADASTRO
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "Fulano",
  "email": "fulano@email.com",
  "password": "123456",
  "role": "CLIENT"
}
###

POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@wjt.com",
  "password": "123456",
  "role": "ADMIN"
}
###

# LOGIN // DAS CONTAS CADASTRADAS
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "admin@wjt.com",
  "password": "123456",
  "role": "ADMIN"
}
###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "fulano@email.com",
  "password": "123456",
  "role": "CLIENT"
}
###

# ATUALIZAR // ADICIONAR ID
PUT http://localhost:3001/users/1
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Fulane",
  "email": "fulane@wjt.com",
  "password": "1234567"
}
###

# DELETAR // ADICIONAR ID
DELETE http://localhost:3001/users/3
Authorization: Bearer 
###

///////////////////////////////////////////////////////////////////////////////////////////////////

GET http://localhost:3001/products
Content-Type: application/json
###

# BUSCAR PRODUTO ESPECIFICO // ADICIONAR ID
GET http://localhost:3001/products/
Content-Type: application/json
###

# CRIAR PRODUTO NA LOJA
POST http://localhost:3001/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5Ad2p0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc4MjQxNjk5MSwiZXhwIjoxNzgyNDE4NzkxfQ.g6ty-DQdrjnk-kO4Uk3CrWyelRG66S6sWiSRuTFouGY

{
  "name": "Jogo de Soquetes",
  "description": "Jogo de Soquetes Estriados 34 Pol com 20 Pecas e Caixa Metalica MTX-135369",
  "price": 949.99,
  "stock": 130,
  "categoryId": 1,
  "imagem": "/images/soquetes.png"
}
###

# ATUALIZAR // ADICIONAR ID
PUT http://localhost:3001/products/2
Content-Type: application/json
Authorization: Bearer 

{
  "name": "Motoserra",
  "description": "A bateria.",
  "price": 599.90,
  "stock": 40
}
###

# DELETAR PRODUTO // ADICIONAR ID
DELETE http://localhost:3001/products/2
Content-Type: application/json
Authorization: Bearer 
###

# CATEGORIAS
GET http://localhost:3001/categories
Content-Type: application/json
###

POST http://localhost:3001/categories
Content-Type: application/json

{
  "name": "Baterias"
}
###
